[versions]
agp = "7.4.0"
lifecycle = "2.4.0"
compile-sdk = "33"

[libraries]
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }

[plugins]
library = { id = "com.android.library", version.ref = "agp" }