[versions]
root = "2.0.14"

[libraries]

keep-api = { module = "tz.co.asoft:keep-api", version.ref = "root" }
keep-file = { module = "tz.co.asoft:keep-file", version.ref = "root" }
keep-browser = { module = "tz.co.asoft:keep-browser", version.ref = "root" }
keep-mock = { module = "tz.co.asoft:keep-mock", version.ref = "root" }
keep-react-native = { module = "tz.co.asoft:keep-react-native", version.ref = "root" }

kash-currency = { module = "tz.co.asoft:kash-currency", version.ref = "root" }
kash-money = { module = "tz.co.asoft:kash-money", version.ref = "root" }

koncurrent-executors-core = { module = "tz.co.asoft:koncurrent-executors-core", version.ref = "root" }
koncurrent-executors-coroutines = { module = "tz.co.asoft:koncurrent-executors-coroutines", version.ref = "root" }
koncurrent-executors-mock = { module = "tz.co.asoft:koncurrent-executors-mock", version.ref = "root" }

koncurrent-later-core = { module = "tz.co.asoft:koncurrent-later-core", version.ref = "root" }
koncurrent-later-test = { module = "tz.co.asoft:koncurrent-later-test", version.ref = "root" }
koncurrent-later-coroutines = { module = "tz.co.asoft:koncurrent-later-coroutines", version.ref = "root" }

kommander-core = { module = "tz.co.asoft:kommander-core", version.ref = "root" }
kommander-coroutines = { module = "tz.co.asoft:kommander-coroutines", version.ref = "root" }

identifier-core = { module = "tz.co.asoft:identifier-core", version.ref = "root" }
identifier-generators = { module = "tz.co.asoft:identifier-generators", version.ref = "root" }

live-core = { module = "tz.co.asoft:live-core", version.ref = "root" }
live-react = { module = "tz.co.asoft:live-react", version.ref = "root" }
live-test = { module = "tz.co.asoft:live-test", version.ref = "root" }

viewmodel-core = { module = "tz.co.asoft:viewmodel-core", version.ref = "root" }

[plugins]
library = { id = "tz.co.asoft.library", version.ref = "root" }
applikation = { id = "tz.co.asoft.applikation", version.ref = "root" }
deploy = { id = "tz.co.asoft.deploy", version.ref = "root" }