[versions]
root = "2.0.13"

[libraries]

cache-api = { module = "tz.co.asoft:cache-api", version.ref = "root" }
cache-file = { module = "tz.co.asoft:cache-file", version.ref = "root" }
cache-browser = { module = "tz.co.asoft:cache-browser", version.ref = "root" }
cache-mock = { module = "tz.co.asoft:cache-mock", version.ref = "root" }
cache-react-native = { module = "tz.co.asoft:cache-react-native", version.ref = "root" }

kash-currency = { module = "tz.co.asoft:kash-currency", version.ref = "root" }
kash-money = { module = "tz.co.asoft:kash-money", version.ref = "root" }

koncurrent-primitives-core = { module = "tz.co.asoft:koncurrent-primitives-core", version.ref = "root" }
koncurrent-primitives-coroutines = { module = "tz.co.asoft:koncurrent-primitives-coroutines", version.ref = "root" }
koncurrent-primitives-mock = { module = "tz.co.asoft:koncurrent-primitives-mock", version.ref = "root" }

koncurrent-later-core = { module = "tz.co.asoft:koncurrent-later-core", version.ref = "root" }
koncurrent-later-test = { module = "tz.co.asoft:koncurrent-later-test", version.ref = "root" }
koncurrent-later-coroutines = { module = "tz.co.asoft:koncurrent-later-coroutines", version.ref = "root" }

expect-core = { module = "tz.co.asoft:expect-core", version.ref = "root" }
expect-coroutines = { module = "tz.co.asoft:expect-coroutines", version.ref = "root" }

identifier-core = { module = "tz.co.asoft:identifier-core", version.ref = "root" }
identifier-generators = { module = "tz.co.asoft:identifier-generators", version.ref = "root" }

live-core = { module = "tz.co.asoft:live-core", version.ref = "root" }
live-react = { module = "tz.co.asoft:live-react", version.ref = "root" }
live-test = { module = "tz.co.asoft:live-test", version.ref = "root" }

viewmodel-core = { module = "tz.co.asoft:viewmodel-core", version.ref = "root" }

[plugins]
library = { id = "tz.co.asoft.library", version.ref = "root" }
applikation = { id = "tz.co.asoft.applikation", version.ref = "root" }
deploy = { id = "tz.co.asoft.deploy", version.ref = "root" }