[versions]
#bom = "1.0.0-pre.480"
bom = "1.0.0-pre.780"
react-types="^18.1.4"

[libraries]
bom = { module = "org.jetbrains.kotlin-wrappers:kotlin-wrappers-bom", version.ref = "bom" }
extension = { module = "org.jetbrains.kotlin-wrappers:kotlin-extensions" }
browser = { module = "org.jetbrains.kotlin-wrappers:kotlin-browser" }
react-core = { module = "org.jetbrains.kotlin-wrappers:kotlin-react-core" }
react = { module = "org.jetbrains.kotlin-wrappers:kotlin-react" }
react-dom = { module = "org.jetbrains.kotlin-wrappers:kotlin-react-dom" }
react-dom-new = { module = "org.jetbrains.kotlin-wrappers:kotlin-react-dom" }
router-dom = { module = "org.jetbrains.kotlin-wrappers:kotlin-react-router-dom" }
css = { module = "org.jetbrains.kotlin-wrappers:kotlin-css" }
styled = { module = "org.jetbrains.kotlin-wrappers:kotlin-styled" }
