[versions]
ktor = "3.0.0-beta-2" # "2.3.12" # "2.3.5"

[libraries]
client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
client-apache = { module = "io.ktor:ktor-client-apache", version.ref = "ktor" }
client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
client-jetty = { module = "io.ktor:ktor-client-jetty", version.ref = "ktor" }
http = { module = "io.ktor:ktor-http", version.ref = "ktor" }
html = { module = "io.ktor:ktor-server-html-builder", version.ref = "ktor" }

server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
