[versions]
##ktor = "3.0.0-beta-2" # "2.3.12" # "2.3.5"
ktor = "2.3.12"

[libraries]
client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
http = { module = "io.ktor:ktor-http", version.ref = "ktor" }
html = { module = "io.ktor:ktor-server-html-builder", version.ref = "ktor" }

server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
