[versions]
asoft = "3.0.0"

[libraries]
kommander-core = { module = "tz.co.asoft:kommander-core", version.ref = "asoft" }
kommander-coroutines = { module = "tz.co.asoft:kommander-coroutines", version.ref = "asoft" }

kollections-interoperable = { module = "tz.co.asoft:kollections-interoperable", version.ref = "asoft" }
kollections-atomic = { module = "tz.co.asoft:kollections-atomic", version.ref = "asoft" }

kevlar-api = { module = "tz.co.asoft:kevlar-api", version.ref = "asoft" }
kevlar-core = { module = "tz.co.asoft:kevlar-core", version.ref = "asoft" }

kase-possible = { module = "tz.co.asoft:kase-possible", version.ref = "asoft" }
kase-optional = { module = "tz.co.asoft:kase-optional", version.ref = "asoft" }
kase-core = { module = "tz.co.asoft:kase-core", version.ref = "asoft" }

koncurrent-executors-core = { module = "tz.co.asoft:koncurrent-executors-core", version.ref = "asoft" }
koncurrent-executors-coroutines = { module = "tz.co.asoft:koncurrent-executors-coroutines", version.ref = "asoft" }
koncurrent-executors-mock = { module = "tz.co.asoft:koncurrent-executors-mock", version.ref = "asoft" }
koncurrent-later-core = { module = "tz.co.asoft:koncurrent-later-core", version.ref = "asoft" }
koncurrent-later-test = { module = "tz.co.asoft:koncurrent-later-test", version.ref = "asoft" }
koncurrent-later-coroutines = { module = "tz.co.asoft:koncurrent-later-coroutines", version.ref = "asoft" }
koncurrent-later-react = { module = "tz.co.asoft:koncurrent-later-react", version.ref = "asoft" }

neat-validation = { module = "tz.co.asoft:neat-validation", version.ref = "asoft" }
neat-formatting = { module = "tz.co.asoft:neat-formatting", version.ref = "asoft" }

keep-api = { module = "tz.co.asoft:keep-api", version.ref = "asoft" }
keep-file = { module = "tz.co.asoft:keep-file", version.ref = "asoft" }
keep-browser = { module = "tz.co.asoft:keep-browser", version.ref = "asoft" }
keep-mock = { module = "tz.co.asoft:keep-mock", version.ref = "asoft" }
keep-react-native = { module = "tz.co.asoft:keep-react-native", version.ref = "asoft" }

lexi-api = { module = "tz.co.asoft:lexi-api", version.ref = "asoft" }
lexi-file = { module = "tz.co.asoft:lexi-file", version.ref = "asoft" }
lexi-console = { module = "tz.co.asoft:lexi-console", version.ref = "asoft" }

kash-currency = { module = "tz.co.asoft:kash-currency", version.ref = "asoft" }
kash-cents = { module = "tz.co.asoft:kash-cents", version.ref = "asoft" }
kash-money = { module = "tz.co.asoft:kash-money", version.ref = "asoft" }

geo-core = { module = "tz.co.asoft:geo-core", version.ref = "asoft" }
geo-languages = { module = "tz.co.asoft:geo-languages", version.ref = "asoft" }
geo-countries = { module = "tz.co.asoft:geo-countries", version.ref = "asoft" }

cinematic-live-core = { module = "tz.co.asoft:cinematic-live-core", version.ref = "asoft" }
cinematic-live-compose = { module = "tz.co.asoft:cinematic-live-compose", version.ref = "asoft" }
cinematic-live-kollections = { module = "tz.co.asoft:cinematic-live-kollections", version.ref = "asoft" }
cinematic-live-react = { module = "tz.co.asoft:cinematic-live-react", version.ref = "asoft" }
cinematic-live-test = { module = "tz.co.asoft:cinematic-live-test", version.ref = "asoft" }
cinematic-scene-core = { module = "tz.co.asoft:cinematic-scene-core", version.ref = "asoft" }

kronecker-core = { module = "tz.co.asoft:kronecker-core", version.ref = "asoft" }

epsilon-core = { module = "tz.co.asoft:epsilon-core", version.ref = "asoft" }
epsilon-fake = { module = "tz.co.asoft:epsilon-fake", version.ref = "asoft" }
epsilon-file = { module = "tz.co.asoft:epsilon-file", version.ref = "asoft" }
epsilon-network-ktor = { module = "tz.co.asoft:epsilon-file", version.ref = "asoft" }

krono-api = { module = "tz.co.asoft:krono-api", version.ref = "asoft" }
krono-kotlinx = { module = "tz.co.asoft:krono-kotlinx", version.ref = "asoft" }

captain-url = { module = "tz.co.asoft:captain-url", version.ref = "asoft" }
captain-navigator-api = { module = "tz.co.asoft:captain-navigator-api", version.ref = "asoft" }
captain-navigator-basic = { module = "tz.co.asoft:captain-navigator-basic", version.ref = "asoft" }
captain-navigator-browser = { module = "tz.co.asoft:captain-navigator-browser", version.ref = "asoft" }
captain-router-core = { module = "tz.co.asoft:captain-router-core", version.ref = "asoft" }
captain-router-react-core = { module = "tz.co.asoft:captain-router-react-core", version.ref = "asoft" }
captain-router-react-dom = { module = "tz.co.asoft:captain-router-react-dom", version.ref = "asoft" }
captain-router-compose-core = { module = "tz.co.asoft:captain-router-compose-core", version.ref = "asoft" }
captain-router-compose-html = { module = "tz.co.asoft:captain-router-compose-html", version.ref = "asoft" }

asterina-color-core = { module = "tz.co.asoft:asterina-color-core", version.ref = "asoft" }
asterina-color-compose = { module = "tz.co.asoft:asterina-color-compose", version.ref = "asoft" }
asterina-size = { module = "tz.co.asoft:asterina-size", version.ref = "asoft" }
asterina-base = { module = "tz.co.asoft:asterina-base", version.ref = "asoft" }
asterina-text = { module = "tz.co.asoft:asterina-text", version.ref = "asoft" }
asterina-brand = { module = "tz.co.asoft:asterina-brand", version.ref = "asoft" }

identifier-core = { module = "tz.co.asoft:identifier-core", version.ref = "asoft" }
identifier-generators = { module = "tz.co.asoft:identifier-generators", version.ref = "asoft" }

[plugins]
library = { id = "tz.co.asoft.library", version.ref = "asoft" }
applikation = { id = "tz.co.asoft.applikation", version.ref = "asoft" }
deploy = { id = "tz.co.asoft.deploy", version.ref = "asoft" }
