[versions]
node-version = "22.0.0-v8-canary20231201483993aba6"
node-url = "https://mirrors.dotsrc.org/nodejs/v8-canary"
platform = "1.3.6"
fetch = "2.6.7" # Beware: updating to 3.x.y has a weird commonjs require/import error
asyncStorage = "1.15.9"
