[versions]
okio = "3.10.2" # "3.9.1"

[libraries]
okio-core = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fake = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
