[versions]
testcontainers = "1.21.3"

[libraries]
core = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
mongodb = { module = "org.testcontainers:mongodb", version.ref = "testcontainers" }
mysql = { module = "org.testcontainers:mysql", version.ref = "testcontainers" }
