[versions]
publish = "0.32.0" # "0.25.2" # https://vanniktech.github.io/gradle-maven-publish-plugin/central/

[plugins]
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
